import React from 'react';
import ReactDOM from 'react-dom';

class Mainn extends React.Component {
    render() {
        return(
            <div>
                <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi cupiditate doloremque doloribus eaque eius et ex harum, iste itaque labore laudantium magnam minus porro possimus praesentium recusandae repellendus suscipit tenetur!</span><span>Accusamus animi consequuntur debitis, deserunt, doloribus eius esse ex ipsam itaque necessitatibus nobis non numquam officiis porro possimus quia quidem repellendus sed similique soluta totam unde veniam voluptatibus. Quidem, sequi!</span><span>Accusamus accusantium alias aperiam aspernatur dolores dolorum facilis itaque iure laborum libero, quas, quidem quis quo rem repudiandae sapiente sed temporibus tenetur ut voluptas? Ea eos facere minus porro. Beatae!</span><span>Consequuntur dolore, exercitationem neque praesentium rem suscipit. Asperiores at enim, eos eum excepturi illo ipsa magnam magni minus modi molestias nesciunt perspiciatis placeat repellat sequi soluta vero? Culpa exercitationem, vel!</span><span>Consectetur consequuntur eligendi excepturi incidunt nihil sunt unde voluptatem voluptatum! Accusantium deserunt, dicta dolores eius explicabo impedit ipsum laboriosam laborum natus odit praesentium reprehenderit repudiandae saepe sint soluta sunt, voluptatibus.</span><span>Ab accusantium adipisci at aut autem eius esse explicabo incidunt iusto labore molestiae nobis nulla numquam officia placeat quaerat, qui quisquam quod repellat repellendus saepe sapiente sed sint sunt voluptates!</span><span>A ab accusantium alias asperiores aspernatur at consectetur dolore doloremque dolores, ducimus eligendi enim ex, expedita id iusto laborum mollitia neque odio provident quaerat qui rem, repellendus sapiente tempore ullam!</span><span>A assumenda dolore ea harum laboriosam laborum maiores, minima mollitia nam pariatur possimus, qui, quidem quisquam ratione temporibus. Ab animi consequuntur corporis hic impedit odio odit officiis praesentium quia tempore!</span><span>A alias architecto cupiditate dicta et expedita nemo non numquam officiis quam quo sapiente, temporibus voluptatem. Commodi enim incidunt nemo, nobis, officia omnis qui recusandae repellendus sed tempora, ullam voluptas!</span><span>A ab accusamus alias amet autem consequuntur cum delectus dignissimos eligendi excepturi facilis id impedit incidunt ipsum iste molestias mollitia natus nobis porro, recusandae rem sed sint ullam veniam voluptatem.</span></p><p>
                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias consequatur deleniti dolore earum ex, fuga incidunt ipsum iusto minima modi nihil nisi, perferendis perspiciatis quam qui quo reiciendis rem voluptatem?</span><span>Aliquid architecto at atque beatae culpa deleniti dolor dolore dolorem dolorum et ex, expedita explicabo, fugiat magni maxime minus modi quibusdam quis quo ratione reiciendis soluta tempora ut voluptas voluptates.</span><span>Delectus et harum, incidunt neque nostrum perferendis recusandae sequi? Ab commodi, et nam nemo officia omnis optio sequi. At dicta dolorem fugit incidunt maxime molestiae odio officia sed suscipit voluptatum.</span><span>Alias autem distinctio earum et eum itaque iure minima recusandae voluptate. Adipisci blanditiis corporis deleniti enim est eveniet fuga id laboriosam omnis, placeat quasi quo reprehenderit soluta suscipit voluptates. Dolorem.</span><span>Accusantium, ad aliquid architecto blanditiis commodi cumque cupiditate, dignissimos dolorem excepturi expedita facilis fuga harum illo illum molestias nam necessitatibus neque perferendis repellat repellendus, sunt vitae voluptates. Commodi, neque, nulla.</span><span>Dolorem eos, ipsum maiores ullam unde voluptatem. Adipisci amet, corporis, deleniti doloremque eaque eligendi eum fugiat illum maxime minima minus nemo, quae qui ratione soluta sunt unde vel velit voluptates.</span><span>Aliquam aut, earum error facere illo in inventore maiores, neque obcaecati, odit officia quibusdam quis quos sint totam veniam voluptatem voluptatibus. Assumenda commodi eos mollitia nam natus quas recusandae temporibus.</span><span>Accusantium asperiores at aut commodi cumque dignissimos dolorem error esse eveniet, excepturi fugiat harum inventore ipsa iusto minima nostrum praesentium quaerat quam quibusdam quidem quisquam suscipit ullam voluptate voluptatem voluptatibus.</span><span>Architecto doloremque, dolorum iure nam nemo quod reprehenderit voluptatem? Fugit, placeat, totam! A adipisci autem blanditiis dolor ea est hic id, illum inventore modi omnis optio quidem tempore ullam veritatis.</span><span>A error iusto qui rem reprehenderit totam veritatis vitae voluptates voluptatibus. Alias consequatur doloremque dolorum ea eligendi enim explicabo, harum iusto magni nesciunt pariatur quam quasi reprehenderit saepe sequi sint.</span></p><p>
                <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dolor dolores, enim libero necessitatibus provident quod sint voluptates voluptatibus! A accusamus eius esse inventore ipsam itaque nihil sequi tempore. Architecto.</span><span>Accusamus aliquid dolorem eum ex facere fugit in incidunt iusto, modi nobis odit, quisquam quo quod repellendus, repudiandae sit unde ut. Eos excepturi nesciunt nobis nostrum, officia quas voluptas voluptatibus.</span><span>Fuga illum possimus provident ut! Ab eveniet ex, excepturi itaque maxime modi obcaecati officiis praesentium quas qui quis reiciendis, saepe temporibus veritatis vero! Eligendi eos fugiat, harum molestias nemo vitae?</span><span>Aliquam atque autem beatae consequuntur ducimus eaque ex fugiat illo, iure minus nemo nesciunt odio omnis placeat praesentium provident quasi qui quidem quo recusandae, rerum sed similique unde velit vero!</span><span>Accusantium dignissimos fugit minima quam, reprehenderit sed ullam? Aspernatur autem culpa impedit ipsam labore laboriosam molestias reiciendis, rerum sunt suscipit. Aliquam aliquid doloremque doloribus eos molestias pariatur repudiandae similique voluptates.</span><span>Ab at atque autem beatae consequuntur cum delectus dolorem dolores eius esse, exercitationem facilis fugiat illo inventore iure iusto minima obcaecati provident, quam quas quis reprehenderit, sint temporibus vero voluptates!</span><span>Ab, aspernatur assumenda aut autem commodi cum, deserunt dolore doloremque doloribus eaque eveniet fugiat fugit iure labore laboriosam magnam nobis non officiis optio quasi qui quo sint tenetur unde, velit?</span><span>Ducimus facere nulla vitae. Architecto blanditiis consectetur dignissimos distinctio, dolore ex explicabo impedit porro possimus quibusdam quidem ratione reprehenderit saepe sint vitae! Aperiam aspernatur aut corporis natus placeat porro, reprehenderit!</span><span>Aliquid architecto atque, dolor, error eveniet, ex hic incidunt ipsum magni obcaecati qui quibusdam quis reprehenderit rerum tempore. Doloribus ipsa ipsam tempora totam! Ea eligendi illo magni numquam quo soluta.</span><span>At deleniti et explicabo facere ipsam numquam, officia quaerat? Debitis magnam necessitatibus nesciunt officia, quae quasi tempora. Facere facilis libero magnam porro quae quasi qui reiciendis rerum tempora, veritatis voluptatum?</span></p>
            </div>
        );
    }
}

ReactDOM.render(
    <Mainn />,
    document.getElementById('root')
);
